"""update_silver_futures_mbo

Revision ID: 0d7e0c9b6a5d
Revises: 1fed7115b2de
Create Date: 2026-02-11 16:00:13.070298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7e0c9b6a5d'
down_revision = '1fed7115b2de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('silver_futures_mbo', 'ts_in_delta',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('silver_futures_mbo', 'sequence',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('silver_futures_mbo', 'sequence',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('silver_futures_mbo', 'ts_in_delta',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
