"""fix_silver_mbo_price_decimal_precision

Revision ID: 1fed7115b2de
Revises: 57124913817c
Create Date: 2026-02-10 15:09:01.379589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fed7115b2de'
down_revision = '57124913817c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('silver_futures_mbo', 'price',
               existing_type=sa.NUMERIC(precision=5, scale=9),
               type_=sa.DECIMAL(precision=6, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('silver_futures_mbo', 'price',
               existing_type=sa.DECIMAL(precision=6, scale=3),
               type_=sa.NUMERIC(precision=5, scale=9),
               existing_nullable=True)
    # ### end Alembic commands ###
