"""added snapshot table and updated tz

Revision ID: 20b9727bdd63
Revises: bec88ad8b2a3
Create Date: 2024-06-07 16:03:02.508226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b9727bdd63'
down_revision = 'bec88ad8b2a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('options_ticker_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=False),
    sa.Column('implied_volatility', sa.DECIMAL(precision=24, scale=20), nullable=False),
    sa.Column('delta', sa.DECIMAL(precision=24, scale=20), nullable=False),
    sa.Column('gamma', sa.DECIMAL(precision=24, scale=20), nullable=False),
    sa.Column('theta', sa.DECIMAL(precision=24, scale=20), nullable=False),
    sa.Column('vega', sa.DECIMAL(precision=24, scale=20), nullable=False),
    sa.Column('open_interest', sa.BigInteger(), nullable=False),
    sa.Column('is_overwritten', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['options_ticker_id'], ['options_tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('options_ticker_id', 'as_of_date', name='uq_options_snapshot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('options_snapshots')
    # ### end Alembic commands ###
