"""add_index_silver_mbo_order_id

Revision ID: 34551fa734e8
Revises: f1b6f8396ef0
Create Date: 2026-02-24 14:40:00.648801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34551fa734e8'
down_revision = 'f1b6f8396ef0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_silver_mbo_order_id', 'silver_futures_mbo', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_silver_mbo_order_id', table_name='silver_futures_mbo')
    # ### end Alembic commands ###
