"""drop_tables

Revision ID: 503562d9f933
Revises: 9c82e662887e
Create Date: 2023-02-24 16:48:01.981195

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op


# revision identifiers, used by Alembic.
revision = "503562d9f933"
down_revision = "9c82e662887e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("option_prices")
    op.drop_table("options_tickers")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "option_prices",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("options_ticker_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("price_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("as_of_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("close_price", sa.NUMERIC(precision=19, scale=4), autoincrement=False, nullable=False),
        sa.Column("open_price", sa.NUMERIC(precision=19, scale=4), autoincrement=False, nullable=False),
        sa.Column("high_price", sa.NUMERIC(precision=19, scale=4), autoincrement=False, nullable=False),
        sa.Column("low_price", sa.NUMERIC(precision=19, scale=4), autoincrement=False, nullable=False),
        sa.Column("volume_weight_price", sa.NUMERIC(precision=19, scale=4), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True
        ),
        sa.Column("is_overwritten", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=True),
        sa.Column("volume", sa.NUMERIC(precision=19, scale=4), autoincrement=False, nullable=False),
        sa.Column("number_of_transactions", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("otc", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["options_ticker_id"],
            ["options_tickers.id"],
            name="option_prices_options_ticker_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="option_prices_pkey"),
        sa.UniqueConstraint("id", name="option_prices_id_key"),
        sa.UniqueConstraint("options_ticker_id", "price_date", "as_of_date", name="uq_options_price"),
    )
    op.create_table(
        "options_tickers",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("underlying_ticker_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("strike_price", sa.NUMERIC(precision=19, scale=4), autoincrement=False, nullable=False),
        sa.Column("options_ticker", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("expiration_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "contract_type", postgresql.ENUM("call", "put", name="optiontype"), autoincrement=False, nullable=False
        ),
        sa.Column("shares_per_contract", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("cfi", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("exercise_style", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("primary_exchange", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["underlying_ticker_id"],
            ["stock_tickers.id"],
            name="options_tickers_underlying_ticker_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="options_tickers_pkey"),
        sa.UniqueConstraint("id", name="options_tickers_id_key"),
        sa.UniqueConstraint("options_ticker", name="options_tickers_options_ticker_key"),
    )
    # ### end Alembic commands ###
