"""add_silver_futures_mbo

Revision ID: 57124913817c
Revises: aa7364d6afa7
Create Date: 2026-02-09 17:10:21.567852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57124913817c'
down_revision = 'aa7364d6afa7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('silver_futures_mbo',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts_recv', sa.DateTime(), nullable=False),
    sa.Column('ts_event', sa.DateTime(), nullable=False),
    sa.Column('rtype', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=1), nullable=False),
    sa.Column('side', sa.String(length=1), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=5, scale=9), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('flags', sa.Integer(), nullable=True),
    sa.Column('ts_in_delta', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_event', 'order_id', 'sequence', name='uq_silver_mbo_event')
    )
    op.create_unique_constraint(None, 'options_quotes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'options_quotes', type_='unique')
    op.drop_table('silver_futures_mbo')
    # ### end Alembic commands ###
