"""updating price precision again

Revision ID: 5f9dbb4c8034
Revises: 98bec8af4a8e
Create Date: 2026-02-11 20:49:47.649908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9dbb4c8034'
down_revision = '98bec8af4a8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('silver_futures_mbo', 'price',
               existing_type=sa.NUMERIC(precision=8, scale=3),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('silver_futures_mbo', 'price',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=sa.NUMERIC(precision=8, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###
