"""tables_back

Revision ID: 74112727120a
Revises: 503562d9f933
Create Date: 2023-02-24 16:54:59.222064

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "74112727120a"
down_revision = "503562d9f933"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "options_tickers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("underlying_ticker_id", sa.Integer(), nullable=False),
        sa.Column("options_ticker", sa.String(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=False),
        sa.Column("strike_price", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("contract_type", sa.Enum("call", "put", name="contracttype"), nullable=False),
        sa.Column("shares_per_contract", sa.Integer(), nullable=True),
        sa.Column("cfi", sa.String(), nullable=True),
        sa.Column("exercise_style", sa.String(), nullable=True),
        sa.Column("primary_exchange", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["underlying_ticker_id"], ["stock_tickers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("options_ticker"),
    )
    op.create_table(
        "option_prices",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("options_ticker_id", sa.BigInteger(), nullable=False),
        sa.Column("price_date", sa.Date(), nullable=False),
        sa.Column("as_of_date", sa.DateTime(), nullable=False),
        sa.Column("close_price", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("open_price", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("high_price", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("low_price", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("volume_weight_price", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("volume", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("number_of_transactions", sa.Integer(), nullable=True),
        sa.Column("otc", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("is_overwritten", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.ForeignKeyConstraint(["options_ticker_id"], ["options_tickers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("options_ticker_id", "price_date", "as_of_date", name="uq_options_price"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("option_prices")
    op.drop_table("options_tickers")
    # ### end Alembic commands ###
