"""changed price schema size

Revision ID: 98bec8af4a8e
Revises: 0d7e0c9b6a5d
Create Date: 2026-02-11 16:45:44.612057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bec8af4a8e'
down_revision = '0d7e0c9b6a5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('silver_futures_mbo', 'price',
               existing_type=sa.NUMERIC(precision=6, scale=3),
               type_=sa.DECIMAL(precision=8, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('silver_futures_mbo', 'price',
               existing_type=sa.DECIMAL(precision=8, scale=3),
               type_=sa.NUMERIC(precision=6, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###
