"""optionstickers_changes

Revision ID: 9c82e662887e
Revises: b4fcc151dd9a
Create Date: 2023-02-24 16:20:49.122725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c82e662887e'
down_revision = 'b4fcc151dd9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options_tickers', sa.Column('options_ticker', sa.String(), nullable=False))
    op.add_column('options_tickers', sa.Column('expiration_date', sa.Date(), nullable=False))
    op.add_column('options_tickers', sa.Column('contract_type', sa.Enum('call', 'put', name='optiontype'), nullable=False))
    op.add_column('options_tickers', sa.Column('shares_per_contract', sa.String(), nullable=True))
    op.add_column('options_tickers', sa.Column('cfi', sa.String(), nullable=True))
    op.add_column('options_tickers', sa.Column('exercise_style', sa.String(), nullable=True))
    op.add_column('options_tickers', sa.Column('primary_exchange', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'options_tickers', ['options_ticker'])
    op.drop_column('options_tickers', 'option_type')
    op.drop_column('options_tickers', 'exp_date')
    op.drop_column('options_tickers', 'option_ticker')
    op.create_unique_constraint(None, 'stock_prices', ['id'])
    op.add_column('stock_tickers', sa.Column('options_imported', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_tickers', 'options_imported')
    op.drop_constraint(None, 'stock_prices', type_='unique')
    op.add_column('options_tickers', sa.Column('option_ticker', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('options_tickers', sa.Column('exp_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('options_tickers', sa.Column('option_type', postgresql.ENUM('call', 'put', name='optiontype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'options_tickers', type_='unique')
    op.drop_column('options_tickers', 'primary_exchange')
    op.drop_column('options_tickers', 'exercise_style')
    op.drop_column('options_tickers', 'cfi')
    op.drop_column('options_tickers', 'shares_per_contract')
    op.drop_column('options_tickers', 'contract_type')
    op.drop_column('options_tickers', 'expiration_date')
    op.drop_column('options_tickers', 'options_ticker')
    # ### end Alembic commands ###
