"""add_daily_contract_volumes_table

Revision ID: 9f72b8857a6e
Revises: bdf5943aa4f5
Create Date: 2026-02-18 11:59:23.352404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f72b8857a6e'
down_revision = 'bdf5943aa4f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_contract_volumes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('total_volume', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'symbol', name='uq_daily_volumes_date_symbol')
    )
    op.create_index('ix_daily_volumes_date_vol', 'daily_contract_volumes', ['trade_date', sa.literal_column('total_volume DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_volumes_date_vol', table_name='daily_contract_volumes')
    op.drop_table('daily_contract_volumes')
    # ### end Alembic commands ###
