"""StockPricesRaw_table

Revision ID: b4fcc151dd9a
Revises: 45ad99804ee9
Create Date: 2023-02-22 12:27:23.266053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fcc151dd9a'
down_revision = '45ad99804ee9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.BigInteger(), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=False),
    sa.Column('close_price', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('open_price', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('high_price', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('low_price', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('volume_weight_price', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('volume', sa.DECIMAL(precision=19, scale=4), nullable=False),
    sa.Column('number_of_transactions', sa.Integer(), nullable=True),
    sa.Column('otc', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_overwritten', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['stock_tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'as_of_date', name='uq_stock_price')
    )
    op.add_column('option_prices', sa.Column('volume', sa.DECIMAL(precision=19, scale=4), nullable=False))
    op.add_column('option_prices', sa.Column('number_of_transactions', sa.Integer(), nullable=True))
    op.add_column('option_prices', sa.Column('otc', sa.Boolean(), nullable=True))
    op.drop_constraint('uq_current_price', 'option_prices', type_='unique')
    op.create_unique_constraint('uq_options_price', 'option_prices', ['options_ticker_id', 'price_date', 'as_of_date'])
    op.drop_column('option_prices', 'number_of_trades')
    op.drop_column('option_prices', 'volumn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option_prices', sa.Column('volumn', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('option_prices', sa.Column('number_of_trades', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_options_price', 'option_prices', type_='unique')
    op.create_unique_constraint('uq_current_price', 'option_prices', ['options_ticker_id', 'price_date', 'as_of_date'])
    op.drop_column('option_prices', 'otc')
    op.drop_column('option_prices', 'number_of_transactions')
    op.drop_column('option_prices', 'volume')
    op.drop_table('stock_prices')
    # ### end Alembic commands ###
