"""add_composite_index_silver_mbo

Revision ID: bdf5943aa4f5
Revises: 5f9dbb4c8034
Create Date: 2026-02-12 17:38:13.593991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf5943aa4f5'
down_revision = '5f9dbb4c8034'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_silver_mbo_symbol_ts_action', 'silver_futures_mbo', ['symbol', 'ts_event', 'action'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_silver_mbo_symbol_ts_action', table_name='silver_futures_mbo')
    # ### end Alembic commands ###
