"""DB Update

Revision ID: bec88ad8b2a3
Revises: 9f80e7629676
Create Date: 2023-07-12 07:00:12.524894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec88ad8b2a3'
down_revision = '9f80e7629676'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_prices', 'volume_weight_price',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_prices', 'volume_weight_price',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               nullable=False)
    # ### end Alembic commands ###
