"""DB Update

Revision ID: cea0cb8a78f5
Revises: 52d25047cded
Create Date: 2023-02-20 17:26:25.532236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea0cb8a78f5'
down_revision = '52d25047cded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'option_prices', ['id'])
    op.create_unique_constraint(None, 'options_tickers', ['id'])
    op.add_column('stock_tickers', sa.Column('ticker', sa.String(), nullable=False))
    op.add_column('stock_tickers', sa.Column('imported', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stock_tickers', sa.Column('type', sa.String(), nullable=False))
    op.add_column('stock_tickers', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('stock_tickers', sa.Column('market', sa.String(), nullable=True))
    op.add_column('stock_tickers', sa.Column('locale', sa.String(), nullable=True))
    op.add_column('stock_tickers', sa.Column('primary_exchange', sa.String(), nullable=True))
    op.add_column('stock_tickers', sa.Column('currency_name', sa.String(), nullable=True))
    op.add_column('stock_tickers', sa.Column('cik', sa.String(), nullable=True))
    op.add_column('stock_tickers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('stock_tickers', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('stock_tickers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'stock_tickers', ['id'])
    op.create_unique_constraint(None, 'stock_tickers', ['ticker'])
    op.drop_column('stock_tickers', 'ticker_symbol')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_tickers', sa.Column('ticker_symbol', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stock_tickers', type_='unique')
    op.drop_constraint(None, 'stock_tickers', type_='unique')
    op.alter_column('stock_tickers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('stock_tickers', 'updated_at')
    op.drop_column('stock_tickers', 'created_at')
    op.drop_column('stock_tickers', 'cik')
    op.drop_column('stock_tickers', 'currency_name')
    op.drop_column('stock_tickers', 'primary_exchange')
    op.drop_column('stock_tickers', 'locale')
    op.drop_column('stock_tickers', 'market')
    op.drop_column('stock_tickers', 'active')
    op.drop_column('stock_tickers', 'type')
    op.drop_column('stock_tickers', 'imported')
    op.drop_column('stock_tickers', 'ticker')
    op.drop_constraint(None, 'options_tickers', type_='unique')
    op.drop_constraint(None, 'option_prices', type_='unique')
    # ### end Alembic commands ###
