"""add_lob_snapshots_table

Revision ID: f1b6f8396ef0
Revises: 40296ab2aa9e
Create Date: 2026-02-18 18:50:22.996371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b6f8396ef0'
down_revision = '40296ab2aa9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lob_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('snapshot_ts', sa.DateTime(), nullable=False),
    sa.Column('mid_price', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('best_bid', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('best_ask', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('spread_ticks', sa.Integer(), nullable=False),
    sa.Column('fm_bid_depth_l5', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('fm_ask_depth_l5', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'symbol', 'snapshot_ts', name='uq_lob_snapshot')
    )
    op.create_index('ix_lob_snap_date_symbol', 'lob_snapshots', ['trade_date', 'symbol'], unique=False)
    op.create_index('ix_lob_snap_ts', 'lob_snapshots', ['snapshot_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lob_snap_ts', table_name='lob_snapshots')
    op.drop_index('ix_lob_snap_date_symbol', table_name='lob_snapshots')
    op.drop_table('lob_snapshots')
    # ### end Alembic commands ###
